version: '3'
services:
  app_server:
    container_name: app-server
    build: ./app-server
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=/srv/app/app.py
      - FLASK_DEBUG=1
      - FLASK_SECRET_KEY=sandbox
    volumes:
      - ./app-server/app:/srv/app
    command: flask run --host=0.0.0.0 --port=5000
    # command: gunicorn wsgi:app --chdir /srv/app -b 0.0.0.0:5000

    # THIS LINE WILL ALLOW DOCKER CONTAINER TO STAY ALIVE WITH NO SERVER RUNNING
    # command: tail -f /dev/null
